[project]
name = "blocklist-compiler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "protobuf>=6.33.5",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "grpcio-tools>=1.78.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.2",
]
